# MIT License

# Copyright (c) 2023 Fork Unstable Media GmbH

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

services:
  php:
    build:
      context: ./docker/php
      args:
        TIME_ZONE: "Europe/Berlin"
    user: 1000:1000
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html/
    networks:
      - kirby
  httpd:
    build:
      context: "./docker/httpd/"
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/:ro
    networks:
      - kirby
  mailhog:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - kirby
networks:
  kirby:
    driver: bridge
