# Each page blueprint must have a title, the title may be different from the file name
title: Beitrag
blueprint: page

extends: layouts/default

image:
  icon: draft
  query: false
num: '{{ page.date.toDate("Ymd") }}'

# Each page can have an icon that is shown in page listings when no preview image is available.
# icon: 

# Page options allow you to control how users can interact with the page.
# Here we prevent changing the page status (the home page cannot be renamed or deleted by default)
# More about page options: https://getkirby.com/docs/reference/panel/blueprints/page#options

status:
  draft:
    label: Entwurf
    text: Der Artikel befindet sich noch im Entwurfsmodus. Er kann nur von Redakteuren mit Zugriff auf das Panel gesehen werden.
  unlisted:
    label: In Überprüfung
    text: Der Artikel ist online und kann über die direkte URL aufgerufen werden. Der Artikel wird aber noch nicht auf der Website aufgelistet.
  listed:
    label: Veröffentlicht
    text: Der Artikel ist online und auf der Website aufgelistet.

tabs:
  content:
    columns:
      sidebar:
        sections:
          children: false
          postMeta:
            type: fields
            fields:
              contactsSelect:
                extends: fields/contacts-select
              tags:
                type: tags
                options:
                  type: query
                  query: site.index.filterBy("template", "in", ["camp", "layout"])
              links:
                extends: fields/links
              downloads:
                extends: fields/downloads
              date:
                label: Erstellt am
                type: date
                default: now
                display: DD.MM.YYYY
              author:
                type: users

      main:
        sections:
          stageSection: false
          mainSectionIntro:
            type: fields
            fields:
              section-headline-content:
                help: false
          modelSection:
            type: fields
            fields:
              text:
                type: textarea
                label: Text
                size: large
              image:
                extends: fields/image
                label: Bild (Optional)
                multiple: false
                layout: cards
          contentSection: false

  settings:
    sections:
      teaserFields: false
      postSettings:
        type: fields
        fields:
          postSettingsTitle:
            type: headline
            label: Einstellungen
          # date:
          #   width: 1/2
          #   label: Erstellt am/um
          #   type: date
          #   time: true
          #   default: now
          #   display: DD.MM.YYYY
