# Each page blueprint must have a title, the title may be different from the file name
title: Beitrag
blueprint: page

# Each page can have an icon that is shown in page listings when no preview image is available.
# icon: 

# Page options allow you to control how users can interact with the page.
# Here we prevent changing the page status (the home page cannot be renamed or deleted by default)
# More about page options: https://getkirby.com/docs/reference/panel/blueprints/page#options

extends: pages/layout

tabs:
  content:
    columns:
      sidebar: false
      main:
        sections:
          mainFields:
            fields:
              stage: false
              
  settings:
    sections:
      teaserFields: false
      postMeta:
        type: fields
        fields:
          postMetaTitle:
            type: headline
            label: Einstellungen
          date:
            width: 1/2
            label: Erstellt am/um
            type: date
            time: true
            default: now
            display: DD.MM.YYYY
