title: Freizeit
blueprint: page
extends: pages/layout

image:
  icon: ⛺

tabs:
  content:
    columns:
      sidebar:
        sections:
          children: false
          postMeta:
            type: fields
            fields:
              contact:
                type: users
                label: Kontaktperson(en)
              links:
                label: Verlinkungen
                type: structure
                fields:
                  title:
                    label: Titel
                    type: text
                    required: true
                  url:
                    label: Ziel
                    type: link
                    required: true
                    options:
                      - page
                      - url
                      - email
                      - tel
          files:
            label: Downloads
            layout: cardlets
            text: "{{ file.title.isNotEmpty ? file.title : file.filename }}"
            info: "{{ file.title.isNotEmpty ? file.filename : '' }}"
            template: download


      main:
        sections:
          modelSection:
            type: fields
            fields:
              facts:
                label: Fakten
                type: structure
                columns:
                  icon:
                    width: 1/5
                  name:
                    width: 2/5
                  value:
                    width: 2/5
                fields:
                  icon:
                    extends: fields/icon
                  name:
                    label: Name des Fakts
                    type: text
                  value:
                    label: Inhalt des Fakts
                    type: text
              campIntro:
                label: Einleitung
                type: textarea
                size: medium
                placeholder: Hier kannst du eine Einleitung für die Freizeit eingeben...
          contentSection:
            type: fields
            fields:
              layouts:
                label: Weiterer Inhalt

