title: Freizeit
blueprint: page
extends: layouts/default

image:
  icon: ⛺

tabs:
  content:
    columns:
      sidebar:
        sections:
          children: false
          postMeta:
            type: fields
            fields:
              links:
                extends: fields/links
              downloads:
                extends: fields/downloads
      main:
        sections:
          stageSection:
            fields:
              stage: false
              teaserTitle:
                label: Titel
                type: text
                icon: title
                width: 1/2
                placeholder: '{{page.title}}'
              teaserDescription:
                label: Beschreibung (Wird nur im Seiten-Teaser angezeigt)
                type: textarea
                buttons: false
                maxlength: 130
                icon: text
                width: 1/2
              heroImage:
                extends: fields/image
                label: Bild
                multiple: false
                layout: cards
                image:
                  cover: true
                required: true
                width: 1/2
              heroLogo:
                label: Logo
                type: files
                uploads:
                  template: image
                query: page.files.filterBy("template", "in", ["image"])
                multiple: false
                layout: cards
                width: 1/2
              heroSublineLabel:
                label: Beschriftung der Unterzeile
                type: text
                width: 1/2
                help: Titel der Unterzeile.
              heroSubline:
                label: Unterzeile
                type: text
                maxlength: 20
                width: 1/2
                help: Wird mit sehr großer Schriftart angezeigt.

          modelSection:
            type: fields
            fields:
              facts:
                label: Fakten
                type: structure
                columns:
                  icon:
                    width: 1/5
                  name:
                    width: 2/5
                  value:
                    width: 2/5
                fields:
                  icon:
                    extends: fields/icon
                  name:
                    label: Name des Fakts
                    type: text
                  value:
                    label: Inhalt des Fakts
                    type: text
              campIntro:
                label: Einleitung
                type: textarea
                size: medium
                placeholder: Hier kannst du eine Einleitung für die Freizeit eingeben...
          contentSection:
            type: fields
            fields:
              blocks:
                label: Weiterer Inhalt

