title: Freizeiten
blueprint: page

extends: layouts/default

image:
  icon: file-document

tabs:
  content:
    columns:
      sidebar:
        sections:
          children:
            label: Freizeiten
            template: camp

      # main:
        # sections:
        #   contentSection:
        #     fields:
        #       stage: 
        #         extends: fields/stage-blocks
        #         fieldsets:
        #           - stage-text

              
  settings:
    sections:
      teaserFields: false
