title: layout-page
blueprint: page
image:
  icon: grid
  back: 'var(--theme-accent)'
  color: 'var(--theme-primary)'

tabs:
  pages: false
  model: false
  content:
    label: Inhalt
    icon: text
    columns:
      main:
        width: 3/4
        sections:
          stageSection:
            type: fields
            fields:
              stage: fields/stage-blocks
          modelSection: false
          contentSection:
            type: fields
            fields:
              layouts:
                extends: fields/blocks
      sidebar:
        width: 1/4
        sections:
          children:
            label: Unterseiten
            type: pages
            template: layout
  settings:
    label: Einstellungen
    icon: cog
    sections:
      teaserFields:
        extends: sections/page-teaser
  seo: seo/page
