title: Inhalt und Kontakt
label: Abschnitt
blueprint: field
preview: fields
wysiwyg: true
icon: angle-up

tabs:
  content:
    label: Inhalt
    fields:
      col1:
        extends: fields/blocks-minimal
      contactsSelect:
        type: multiselect
        label: Kontakte auswählen
        layout: list
        options:
          type: query
          query: site.contacts.toStructure
          text: "{{ item.contact.toObject.subject }} ({{ item.contact.toObject.name }})"
          value: "{{ item.customUuid }}"
      contact:
        type: structure
        label: Kontakt
        fields:
          user:
            type: users
            label: Kontakt
            min: 1
            max: 1
          email:
            type: email
            label: E-Mail
            help: 'E-Mail-Adresse des Ansprechpartners'
          phone:
            type: text
            label: Telefon
            help: 'Telefonnummer des Ansprechpartners'
          subject:
            type: text
            label: Themengebiet
  advanced: tabs/blocks-advanced
