title: Standard
label: Abschnitt
blueprint: field
preview: fields
wysiwyg: true
icon: angle-up

tabs:
  content:
    label: Inhalt
    fields:
      col1:
        extends: fields/blocks
  advanced: tabs/blocks-advanced
