title: Inhalt und Kontakt
label: Abschnitt
blueprint: field
preview: fields
wysiwyg: true
icon: angle-up

tabs:
  content:
    label: Inhalt
    fields:
      col1:
        extends: fields/blocks-minimal
      contactsSelect:
        extends: fields/contacts-select
        help: "Wähle eine oder mehrere Kontaktpersonen, die neben dem Inhalt angezeigt werden."
  advanced: tabs/blocks-advanced
