title: Site
blueprint: site
tabs:
  main:
    icon: page
    label: Navigation
    columns:
      - width: 2/3
        sections:
          pages:
            label: pages
            type: pages
            info: '/{{ page.slug }}'
            create:
              - layout
            templates:
              - home
              - layout
              - blogposts
              - camps
              - events
          errorPages:
            label: Fehlerseite
            type: pages
            info: '/{{ page.slug }}'
            templates:
              - error
            create: false
            image: icon
          images:
            label: Bilder
            type: pages
            info: '/{{ page.slug }}'
            templates:
              - images
            create: false
            image: icon
          camps:
            label: Freizeiten
            type: pages
            layout: cards
            info: '/{{ page.slug }}'
            parent: site.find('freizeiten') ?? site.children.template('camps').first
            templates:
              - camp
            image:
              query: page.myTeaserImage
              cover: true
      - width: 1/3
        sections:
          posts:
            label: Beiträge
            type: pages
            flip: true
            info: "{{ page.date.toDate('d.m.Y') }}"
            parent: site.find('blog') ?? site.children.template('blogposts').first
            templates:
              - blogpost
  seo:
    label: SEO-Voreinstellungen
    extends: seo/site

  global: programmatic/global-settings

  admin: programmatic/admin-tools
